export enum ErrorCode {
  INVALID_INTENT = "INVALID_INTENT",
  SLOT_MISSING = "SLOT_MISSING",
  SLOT_AMBIGUOUS = "SLOT_AMBIGUOUS",
  TASK_NOT_FOUND = "TASK_NOT_FOUND",
  TASK_STATUS_INVALID = "TASK_STATUS_INVALID",
  TASK_ALREADY_TERMINAL = "TASK_ALREADY_TERMINAL",
  IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT",
  BROWSER_TIMEOUT = "BROWSER_TIMEOUT",
  SELECTOR_NOT_FOUND = "SELECTOR_NOT_FOUND",
  PAGE_UNEXPECTED = "PAGE_UNEXPECTED",
  LOGIN_REQUIRED = "LOGIN_REQUIRED",
  HUMAN_ACTION_REQUIRED = "HUMAN_ACTION_REQUIRED",
  NO_TRAIN_MATCHED = "NO_TRAIN_MATCHED",
  ORDER_SUBMIT_FAILED = "ORDER_SUBMIT_FAILED",
  INTERNAL_ERROR = "INTERNAL_ERROR"
}
